services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5252:5252"
    environment:
      - PORT=5252
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3232:3232"
    environment:
      - PORT=3232
      - REACT_APP_API_URL=http://localhost:5252/api
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
